### PR TITLE
Get all documents fix

### PR DESCRIPTION
**Pull request by lapistano**
It came to my attention that it is currently not possible to get all documents of a search result or an index returned by using getContents(). This is because of the fact that ElasticSearch it self limits the result set to 10 documents. 
This can only be increased by setting a new limt (»size« in ES language). Despite my thoughts setting it to 0 (zero) does not in creases the number of returned documents to all but actually make ES to return zero documents in the result set. Setting to to a big number instead, will bring the expected result.
Unfortunately the big number has to be higher than the amount of expected documents or ridiculously high to be sure to get all documents, but not too high to make ES crash with a memory limit exceeded exception ... tricky.

reference: http://stackoverflow.com/questions/8829468/elastic-search-query-to-return-all-records

### CODE REVIEW

**Comment by adri** [comment]
This changes relates to https://github.com/liip/LiipRegistryAdaptor/pull/11

**Comment by adri** [comment]
There is something wrong with the existing MySQL tests. In the test `register()` is called with an array (but it expects a string) and the `NoOpDecorator` is used which doesn't do a conversion. So when building the MySQL insert it crashes. See following log:

```
There were 2 errors:

1) Liip\Drupal\Modules\Registry\Database\MySqlTest::testRegister
Array to string conversion

/Volumes/Work/workspace/LiipDrupalRegistryModule/src/Liip/Drupal/Modules/Registry/Database/MySql.php:53
/Volumes/Work/workspace/LiipDrupalRegistryModule/Tests/Liip/Drupal/Modules/Registry/Database/MySqlTest.php:292

2) Liip\Drupal\Modules\Registry\Database\MySqlTest::testReplace
Array to string conversion

/Volumes/Work/workspace/LiipDrupalRegistryModule/src/Liip/Drupal/Modules/Registry/Database/MySql.php:174
/Volumes/Work/workspace/LiipDrupalRegistryModule/Tests/Liip/Drupal/Modules/Registry/Database/MySqlTest.php:380

--


There was 1 failure:

1) Liip\Drupal\Modules\Registry\Database\MySqlTest::testRegisterExpectingException
Failed asserting that exception of type "PHPUnit_Framework_Error_Notice" matches expected exception "\Liip\Drupal\Modules\Registry\RegistryException". Message was: "Array to string conversion".
```

**Comment by lapistano** [comment]
Thx for pin pointing this circumstance .. I agree this is a bug .. pls open an issue.

**Comment by adri** [comment]
Created bug #27

**Pull request merged**
